export const FETCH_OPTION_GROUPS = {
  PENDING: 'FETCH_OPTION_GROUPS_PENDING',
  SUCCESS: 'FETCH_OPTION_GROUPS_SUCCESS',
  FAILED: 'FETCH_OPTION_GROUPS_FAILED'
}

export const DIALOG_TOGGLE = 'DIALOG_TOGGLE'
export const ON_EDIT_OP_GROUP_ROW = 'ON_EDIT_OP_GROUP_ROW'

export const CREATE_OPTION_GROUP = {
  PENDING: 'CREATE_OPTION_GROUP_PENDING',
  SUCCESS: 'CREATE_OPTION_GROUP_SUCCESS',
  FAILED: 'CREATE_OPTION_GROUP_FAILED'
}

export const UPDATE_OPTION_GROUP = {
  PENDING: 'UPDATE_OPTION_GROUP_PENDING',
  SUCCESS: 'UPDATE_OPTION_GROUP_SUCCESS',
  FAILED: 'UPDATE_OPTION_GROUP_FAILED'
}

export const DELETE_OPTION_GROUP = {
  PENDING: 'DELETE_OPTION_GROUP_PENDING',
  SUCCESS: 'DELETE_OPTION_GROUP_SUCCESS',
  FAILED: 'DELETE_OPTION_GROUP_FAILED'
}
