export const FETCH_DRINK_OPTIONS = {
  PENDING: 'FETCH_DRINK_OPTIONS_PENDING',
  SUCCESS: 'FETCH_DRINK_OPTIONS_SUCCESS',
  FAILED: 'FETCH_DRINK_OPTIONS_FAILED'
}

export const DIALOG_TOGGLE = 'DIALOG_TOGGLE'
export const ON_EDIT_DRINK_OPTION_ROW = 'ON_EDIT_DRINK_OPTION_ROW'

export const CREATE_DRINK_OPTION = {
  PENDING: 'CREATE_DRINK_OPTION_PENDING',
  SUCCESS: 'CREATE_DRINK_OPTION_SUCCESS',
  FAILED: 'CREATE_DRINK_OPTION_FAILED'
}

export const UPDATE_DRINK_OPTION = {
  PENDING: 'UPDATE_DRINK_OPTION_PENDING',
  SUCCESS: 'UPDATE_DRINK_OPTION_SUCCESS',
  FAILED: 'UPDATE_DRINK_OPTION_FAILED'
}

export const DELETE_DRINK_OPTION = {
  PENDING: 'DELETE_DRINK_OPTION_PENDING',
  SUCCESS: 'DELETE_DRINK_OPTION_SUCCESS',
  FAILED: 'DELETE_DRINK_OPTION_FAILED'
}
