export const FETCH_DRINKS_MENU = {
  PENDING: 'FETCH_DRINKS_MENU_PENDING',
  SUCCESS: 'FETCH_DRINKS_MENU_SUCCESS',
  FAILED: 'FETCH_DRINKS_MENU_FAILED'
}

export const DIALOG_TOGGLE = 'DIALOG_TOGGLE'
export const ON_EDIT_DRINK_ROW = 'ON_EDIT_DRINK_ROW'

export const CREATE_DRINK = {
  PENDING: 'CREATE_DRINK_PENDING',
  SUCCESS: 'CREATE_DRINK_SUCCESS',
  FAILED: 'CREATE_DRINK_FAILED'
}

export const UPDATE_DRINK = {
  PENDING: 'UPDATE_DRINK_PENDING',
  SUCCESS: 'UPDATE_DRINK_SUCCESS',
  FAILED: 'UPDATE_DRINK_FAILED'
}

export const DELETE_DRINK = {
  PENDING: 'DELETE_DRINK_PENDING',
  SUCCESS: 'DELETE_DRINK_SUCCESS',
  FAILED: 'DELETE_DRINK_FAILED'
}
